import Head from "next/head";
// import Image from "next/image";
import { GetStaticProps } from "next";
// import Link from "next/link";

import ListPosts from "../components/ListPosts";
import PostCard from "../components/PostCard";
import { getAllPosts, Post } from "./api/posts";

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>Rafael Campos de Bastiani - Blog</title>
      </Head>

      <ListPosts>
        {posts.map(({ slug, title, description }: Post) => (
          <PostCard {...{ slug, title, description }} key={slug} />
        ))}
      </ListPosts>
    </>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <ul>
    //       {posts.map((post: Post, idx: any) => (
    //         <li key={idx}>
    //           <Link href={`/posts/${post.slug}`}>
    //             <a>{post.title}</a>
    //           </Link>
    //           <br />
    //           <b>{post.description}</b>
    //         </li>
    //       ))}
    //     </ul>
    //   </main>
    // </div>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const posts = await getAllPosts();

  return {
    props: {
      posts,
    },
  };
};
